#include "enum.h"

using std::cout;
using std::endl;

void Scene::text_color_change(int color_number) { 
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color_number);
}


void Scene::show_StartIntro() {
	cout << endl;
	cout <<"                 ,i200a;                                                                       .:MMMMMM;:                                             " << endl;
	cout <<"                 ,2MMMMMMi                    i8MSi                                            ,,MM   MM:,                                            " << endl;
	cout <<"                 .MM   ;MM:  ,SWMBX.  ;SXWM8;,:XM7;                                            ,iMB:XXM@.  :0MMMM7,  .SWWa;, .rXS@MZ;,                " << endl;
	cout <<"                 .MM    ZM; .MM@BMMB. iMMMMM7; Z0.                                             ,;MMMMMMS . WMZ  MM.;,MMB8MMi..XMM@MM7;                " << endl;
	cout <<"                 :M@    MM, ,MM   MM. iMMi     MM,                                             ,7MX   ZMrr.MMM@WZS:i2M7  MM8 ..MM                     " << endl;
	cout <<"                 iMM8WMMM.  ,ZMMWMMZ, iMM;     MMi                                             :7M8   @Mr:.aMM      ;MMMMaMM,; MM.                    " << endl;
	cout <<"                .;ZBMMai     .;8BZ;.  i20;.   iaMr:                                            :;MMMMMMS,  .r0MMMX: .:Sai 7W;:,aZi                    " << endl;
	cout <<"                                                                    .,,..                                                                             " << endl;
	cout <<"                                                           i7a0W@MMMMMMMMMM@W0ZXi.                                                                    " << endl;
	cout <<"                                                      .rZWMMMW82Xrii:,,,:i;7SZB@MM@ZX,                                                                " << endl;
	cout <<"                                                   .XBMMWa;,                    .;2WMM@a:                                                             " << endl;
	cout <<"                                                 rBMM8r.                             ;ZMMWX                                                           " << endl;
	cout <<"                                               S@MB7                                    ;0MMa,                                                        " << endl;
	cout <<"                                             XMM8i                                        ,ZMMa.                                                      " << endl;
	cout <<"                                           ;BMBi                                            .ZMMX                                                     " << endl;
	cout <<"                                          aMMX                                                iWM0.                                                   " << endl;
	cout <<"                                        .BM0,                                                    aM@i                                                 " << endl;
	cout <<"                                      ,WMa                                                        XM@7                                                " << endl;
	cout <<"                                     ,@MS                                                          ;@@7                                               " << endl;
	cout <<"                                     WM2                                                             r@@;                                             " << endl;
	cout <<"                                    W@7                                                              ,W@;                                             " << endl;
	cout <<"                                   BWX                                                                iWW,                                            " << endl;
	cout <<"                                  :WW:";
	this->text_color_change(14);
	cout <<"                      PRESS ANY KEY TO START";
	this->text_color_change(15);
	cout <<"                     BWX" << endl;
	cout <<"                                  rWB                                                                  ZWa                                            " << endl;
	cout <<"                                  XW0                                                                  aW8                                            " << endl;
	cout <<"                                  2W8                                                                  aW8                                            " << endl;
	cout <<"                                  XWB                         .rr;::ii,i;7X.                           ZBZ                                            " << endl;
	cout <<"                                  ;WW                        ia. 8i:::iZX  Z,                          0WS                                            " << endl;
	cout <<"                                   WWr                       Z  X:      i2 :2                         .BW;                                            " << endl;
	cout <<"                                   ZWZ                       Si a         8S,                         XWB                                             " << endl;
	cout <<"                                   ;@W,                       ;B.         .a                          BW2                                             " << endl;
	cout <<"                                    0@Z                       .2   -   -   2.                        SWW                                              " << endl;
	cout <<"                                    ,@@r                      2,     ▽    Z.                       ,WW7                                              " << endl;
	cout <<"                                     X@@:                     iX          7:                        BWZ                                               " << endl;
	cout <<"                                      aMW. ..,,,,,:,,:::,::,,,.X8rii:ii;XZr.:iiiiiiiiiiii;;;;;;;i,.8W0                                                " << endl;
	cout <<"                                       ZMW8X2aZZZZZZZZaaZaaaaa2X2aMr...  0SS22222222222222222SSXr2W@0                                                 " << endl;
	cout <<"                                        2MB:                     .7      :;                      Z@8                                                  " << endl;
	cout <<"                                         r@M2                    2.       Z                    X@M2                                                   " << endl;
	cout <<"                                          .0MW;                  Z        X;                 i0MW;                                                    " << endl;
	cout <<"                                            7@M0i                8        X;               ,ZMM2                                                      " << endl;
	cout <<"                                              SMMBr              ,2S;X;X;2a              i8MMa.                                                       " << endl;
	cout <<"                                                XWMMa:            X, Z a  2           ,SWM@2.                                                         " << endl;
	cout <<"                                                  iZMMMZr.        X  X X  X.      .;aWMM8r                                                            " << endl;
	cout <<"                                                     iaWMM@0Sr:.  2.,X 7  X  ,;XZWMMWZr                                                               " << endl;
	cout <<"                                                        .;2BMMMMMWMMM@ZMMMMWMMM@0ar,                                                                  " << endl;
	cout <<"                                                              :i7XXXXaZ2SXX7;:.                                                                       " << endl;

	_getch(); // 아무키나 누르면 다음 코드로 넘어가는것
	system("cls"); // 화면 클리어
}

void Scene::show_MainIntro() {
	printf("                                                                   \n          ::BBQBBBi..                      :iv::        . BBs:7RBB.:\n          .sBP iJBB1.     ...     .  ..   ..BB2:        . BB    BB.:  .:qBBj..     ..      .  ... .\n         . QB:    BB....UBBBBBi..:vBBBBBK.: .i :        . BBEBBBQv   .2BBUPBB.. .rBBBBQr. :iBQBBBB::\n         . BB .   gBr:.UBQ::rBB:: vBBrrDI.i BB..        : BBvKDBBR ..iBBr:5BBi:.7BB: QBB . .BQU:PS:.\n    =====. BB    :BB r EBY   QB7 . BB .   ..BB .        ..QB    uBK.:7BBBg5r:.i QB: :BBB: . BB   ::================================================\n    =====:.BBgDBBBBr. ..BBBQBBD. . BB..   :.BB..        :.BQ    BB7.: BBBrir:: .iQBBBEjQB r BQi. ..================================================\n    ||   .:IbBBBMs..   ..7dQXi . .:Pb:.   .:bB::        ..QBBBQBB1.. ..vRBBBZ:  .:Y2i  gP::.sM::                                                 ||\n    ||                                        .          ..:7JJi.            .                                                                   ||\n    ||                                                                                                                                           ||\n    ||                                                                                                                                           ||\n    ||                                                                                                                                           ||\n");
	cout <<"    ||                                                                                                                                           ||" << endl;
	cout <<"    ||                                                                                                           .rr    .     .                  ||" << endl;
	cout <<"    ||                                                                                                            LvBJvr7JUiIj.7s                ||" << endl;
	cout <<"    ||                                                                                                          2::s.      .1I: M                ||" << endl;
	cout <<"    ||                                                                                                          7Qi     .     :QL                ||" << endl;
	cout <<"    ||                                                                                                        sI:              :U                ||" << endl;
	cout <<"    ||                                                                                                      JX:    --    --    .d                ||" << endl;
	cout <<"    ||                                                                                                    .g:                  vJ                ||" << endl;
	cout <<"    ||                                                                                                    P:        ▽        .R                 ||" << endl;
	cout <<"    ||                                                                                                    v1                  b                  ||" << endl;
	cout <<"    ||                                                                                                     51.             .KQ:                  ||" << endl;
	cout <<"    ||                                                                                                      :jjvi:.....::7Ur7I:s                 ||" << endl;
	cout <<"    ||                                       게       임       시       작                                      .:BQ::iii.   P 2:                ||" << endl;
	cout <<"    ||                                                                                                           u.U         :1 R                ||" << endl;
	cout <<"    ||                                                                                                          .s.s          M iU               ||" << endl;
	cout <<"    ||                                                                                                          b K           P. Q               ||" << endl;
	cout <<"    ||                                                                                                         :1.S           rs rI              ||" << endl;
	cout <<"    ||                                                                                                         g b            .d  M.             ||" << endl;
	cout <<"    ||                                                                                                        Ji S            .P  .M             ||" << endl;
	cout <<"    ||                                       게       임       종       료                                   .Z iv            :S   7J            ||" << endl;
	cout <<"    ||                                                                                                       Z  rr            P     Z            ||" << endl;
	cout <<"    ||                                                                                                      Q   .j           XQrKgq2B            ||" << endl;
	cout <<"    ||                                                                                                      XBBQBB7..    .iLsLvLBBB57            ||" << endl;
	cout <<"    ||                                                                                                        :i::K:ivQriB.   E                  ||" << endl;
	cout <<"    ||                                                                                                           .Y   g  P    Y7                 ||" << endl;
	cout <<"    ||                                                                                                           iu   d  D     g                 ||" << endl;
	cout <<"    ||                                                                                                           i2   D  E     g                 ||" << endl;
	cout <<"    ||                                                                                                           Q    Z  g     g                 ||" << endl;
	cout <<"    ||                                                                                                          :P   :S  g    .Z                 ||" << endl;
	cout <<"    ||                                                                                                          q.   sr :U    7s                 ||" << endl;
	cout <<"    ||                                                                                                         .D    g  5riPDgB                  ||" << endl;
	cout <<"    ||                                                                                                         .BBBBBj  .ZBBBS                   ||" << endl;
	cout <<"    ||                                                                                                           .::                             ||" << endl;
	cout <<"    ||                                                                                                                                           ||" << endl;
	cout <<"    ===============================================================================================================================================" << endl;
	cout <<"    ===============================================================================================================================================" << endl;
}

void Scene::show_Scenario() {
	char a[] = { "                                   s.                           5                                             2   :r  S                              P                                    ;                            r                                             i   ,:  s                              P                                    :r                            s;.                                          2   ;;  S                              P                                     :r:..                         ,;;r.                                       X   ;;  5                              P                                       .,,S:                          5                                        2   ;;  S                              P                                          s                           s                                        2   r:  5                              P                                          2                           i                                        5   ;:  5                              P                                          .r;:.....:,                 S3.       ;S                  ,5;.       5   r:  2                              P                                             .,,:,:.rr.     ,;r;;.. .r: ;r:,,.,r;,i.     ,rr;,,...:r; .;;;;;;:.i   r:  S                              P                                                                                                              .i   s,  S                              P                                      ,,                                                                      .i   i.  2                              P                                      2s:                                                                     ,s   i.  5                              P                                     s. r;                                                                    ,s   S   2                              P                      :.            ,r   r:            :                                                      :r   i   S                              P                     .S,;;.         i     S           ;9,                                                     :r   5   5                              P                      s   ;r.      :;     .s        .s .r                                                     :;   S   S                              P                      i    .rr.    S   :;  i.      :s  .r                                                     :;   5   5                              P                      i      .r;  ;,   ;:  .i     r;    i                                                     ;;   S   5                              P                      i        ,r:s    ;:   i.   i,     i                                                     ;;   2   2                              P                      i   .;     ss    ;:   .r ,s       5                                                     r:   5   5                              P                      r,   i.    ;,    ;:    i:r     s. i                                                     ;:   2   5                              P                      ,;    i    s     ::    s2      s  i                                                     r:   5   S                              P                       S    s.  .r     ;:    :;      i  s.                                                    r:   2   5                              P                       i    .s  .r     ;:     S     .r  r,                                                Z   s,   2   5                              P                       ;;    S. .r     ;:     s.    ,;  ;:                                              Z     r,   2   2                              P                        5    .; ,;     :;     :;    r,  r,                          ,:;:;::.,,;:      Z       i.   5   2                              P                        ::      .r     ,i      S    i   r.                     r::Sr:.   .,rX; ,i   Z         i.   2   2                              P                        .2       s      ;      S   ,;   s.                    i. ;:          :i  i            S.   5   5                              P                     :;:;;r      s             2        5;2:                  r,;.             i.i            i.   2   2                              P                     i  .,S;;:::,5,,,.,..      ,  ..,,:si,:,;                  r5               H             5    S   5                              P                     i         ....,,,,::;:;;;:::;::,,.     i.                 .;               r.            S    5   2                              P                     i                                      ;:                 ,r    -    -     ,r            2   .i   2                              P                     s,                                     :;                 r,      ㅅ        i            5   .S   X                              P                      :5::;:;;;:;:;:;;;;;:;;;;;;;:;;;::.... r,                 S                r;            2   .i   5                              P                       i                             ..,,.X;,                  s,              ;s             2   .i   2                              P                       s                                  i                     2.         .;i5.              X   .s   5                              P                       ;:                                :;                      r:. ..,:;;:,S.;              2   ,s   2                              P                        S                                s.                       ,#i,,..    s ;:             2   ,r   2                              P                        i                                S                       ,:s         ;: 5             2   ,r   X                              P;::::,,..               ,;                              ;:                     .r,:;          5  S            2   :r   2                              P ..,,::;:;;;;;;;;;::,,.. X                              i                    :r: ;;           ;:  S.          5   :r   X                              P                  ..,,:,:2:                            .r                  :r, ,r.            .r   i,         5   :r   2                              P                          i                            5,                 ;   ;;               3    s;        S   :;   2                              P::;;;;;;;::::,,..         s                            2,:;;;;;;;:;::,,..,HS5rr                @     ;;       5   ;;   2                              P            ..,,:::;;;;;;:iHr:,                    ..:r;           ..,,:,,s@@@               .i,;     :      .i   ;;   X                              P;;;;;;;::,,..                .;:;;;:;;rrrr23X22iirr;:.                       ;;            .rr;r;@@@@@@;...  .5   ;;   2                              P       ..,,::::;;;;;;;::,,..                     ..,,::;;;;;;;:....      .:;:.;;.        :Ar   2   ,s95.,::;:rS;;;X:   X                              P                      ..,.:,::;;;;;;;:::,,.                    H#s:;isS92:.     ;hAiirr;i2:   ,;                  ;:   2                              P                                       .,,,::;;;;;;;:;::,,..   s@@G           .;:.   ,sX,    .X;::,,....          ;:   2                              P                                                      ..,,::;;:.X@@@&      ,;:.     :;,    .s:    ..,,::::;;;;;;;:h:   5                              P                                                                  r@@@..:r:ii;:;ii;;.     ;2                           2                              P                                                                     .,,.  @@#5         .ri,:;;;;;;::::.,..            5                              P                                                                           3@@@@r     ,s;          ...,,,::;;;;;;;;;:,,A                              P                                                                            ;@@@@@; ,r;                            ...,,                              P                                                                              ,X#@@r:                                                                 PU" };

	int i = 0;
	for (i = 0; a[i] != '\0'; i++)
	{
		if (a[i] == 'P')
		{
			a[i] = '|';
		}
	}
	for (i = 0; a[i] != '\0'; i++)
	{
		if (a[i] == '|')
		{
			a[i + 1] = '\n';
		}

		printf("%c", a[i]);
	}
	cout <<"------------------------------------------------------------------------------------------------------------------------------------------------------" << endl;

	cout << endl;
	cout << endl;
	cout << endl;
	cout <<" 평화로운 어느날, 공주님의 집에 도리베어가 살고있엇어요.                                                                          (넘어갈려면 키 입력)";
	cout << endl;
	cout << endl;
	cout << endl;
	_getch();
	system("cls");


	cout <<"                                                                                                  .X02.      77                  8X                  |" << endl;
	cout <<"                                                                                                 X8:                            82                   |" << endl;
	cout <<"                                                                                               .Br                             20                    |" << endl;
	cout <<"                                                                                              .B.                             .B                     |" << endl;
	cout <<"                                                                                              B.                              X7                     |" << endl;
	cout <<"                                                                                             B:                 7          rX7B                      |" << endl;
	cout <<"                                                                                            Bi                 .B            .Br                     |" << endl;
	cout <<"                                                                                           B7                   B              Bi                    |" << endl;
	cout <<"                                                                                          87     7S2227         Z7              B                    |" << endl;
	cout <<"                                                                                         rM     B7    rB777r.    Bi             S2                   |" << endl;
	cout <<"                                                                                         B.    B:    02:. .:07    87            .B                   |" << endl;
	cout <<"                                                                                         B    M2    B:       B0227.2X            B                   |" << endl;
	cout <<"                                                                                        70   .2    B:      7Zi    rr.27.         B                   |" << endl;
	cout <<"                                                              r2XS2.                    8:        87      M2      rS7777i       :B                   |" << endl;
	cout <<"                                                             M2.  :Bi                   B        iB     :B.     0X.  .M.        B.                   |" << endl;
	cout <<"                                                   i22222i  :M      B                   2X       B.    :B      B:      7       X2                    |" << endl;
	cout <<"                                          .i:    XZ2.. .:7SXMB      B                    0X     70     B      B.   :iriiii    rB                     |" << endl;
	cout <<"                                        70X77X27Bi          .r00:  2M                     r02r77B     02     B  rS2ri...ir.  .B                      |" << endl;
	cout <<"                                       BS     BZ               .X0MX                        .:. M     B     27.X:            B                       |" << endl;
	cout <<"                                      20     rB                   MX        202.                B    27     B 02:.         .B.                       |" << endl;
	cout <<"                                      XZ     B:                    7B      ZBBBB7               i07: Bi     B   .7777i   :2M                         |" << endl;
	cout <<"                                       08:   B             72 7S    :B    .8iBBBB                 :720B.    0X      Br2227:                          |" << endl;
	cout <<"                                        .2077B      S       rBB.     2M   22 XBBB:                     XX7. 0S227iiB.                                |" << endl;
	cout <<"                                           7B    .2B7       r2.0M.    B   B    rB.                       i22i   .:i                                  |" << endl;
	cout <<"                                           B      MM7X7         .     Mi 0X     B                                                                    |" << endl;
	cout <<"               2S          8B             :B     .B   : :8B           B rB     Br                                                                    |" << endl;
	cout <<"               .BX.        BBi            7Z            7BB           BX0     MX                                                                     |" << endl;
	cout <<"                M:X0:     B7 B            :B                         BB:     BS                                                                      |" << endl;
	cout <<"                Xr .2XX2S07  :B2riiXX      B:                      .BZ     7B:                                                                       |" << endl;
	cout <<"                7X     .       ..:BB        B.                   .08B7   :M0                        ii                                               |" << endl;
	cout <<"                S2               M7         .B7               .2Z0:  iMXS2                          2Z                                               |" << endl;
	cout <<"                B.              02            2B2         .i20Xr       B2                           2S      .                                        |" << endl;
	cout <<"               :M            .: B               70X27770BMBX            8X                          BB     B7                                        |" << endl;
	cout <<"               B772S27     002r7Br                    XBr  8             XB                        :BBi  :XB.                                        |" << endl;
	cout <<"             :B8:.   rB7 .Bi    :7                  :M7    B              7B             7M       2B  2XS2 Zi                                        |" << endl;
	cout <<"             7.        B2B                        78X    iZB:              rB            .8BMr77X02        .B                                        |" << endl;
	cout <<"                        Br                 .:ir2SSr    .M0 22               B               Bi .            iBi                                      |" << endl;
	cout <<"                        B:                08..       .0M:  22               B2               B                8B:                                    |" << endl;
	cout <<"                        B2                .BBBBBX. r8Z:    X2               B7B:             B.            7X2i0B.                                   |" << endl;
	cout <<"                        B7                  XBBBBB07.      7Z              Zr  B2            Mr           BX                                         |" << endl;
	cout <<"                                                            B             2B    B2           B   ...     ZX                                          |" << endl;
	cout <<"                                                            B7           B2 B    Br         .B22X222XXS. B                                           |" << endl;
	cout <<"                                                             B:       .XB:  XS    B        .B7        :0BM                                           |" << endl;
	cout <<"                                                              077::i20X:     B    BX                    0B                                           |" << endl;
	cout <<"                                                               080B:.        B   BBB                     B                                           |" << endl;
	cout <<"                                                              82 72          87 7BBS                     i                                           |" << endl;
	cout <<"                                                             B2  B:          .B BBB                                                                  |" << endl;
	cout <<"                                                           .Br   B            02BB.                                                                  |" << endl;
	cout <<"-----------------------------------------------------------------------------------------------------------------------------------------------------|" << endl;

	cout << endl;
	cout << endl;
	cout << endl;
	cout <<" 저런! 공주님이 또 화가 났나 봐요. 도리베어 한테 화를 풀고 있네요                                                                 (넘어갈려면 키 입력)";
	cout << endl;
	cout << endl;
	cout << endl;
	_getch();
	system("cls");


	cout <<"                                                                                                                                                     |" << endl;
	cout <<"::rri:.                                                                                                                                              |" << endl;
	cout <<"BBBBQBBBBBEr                                                            .r7sv7i:                                                                     |" << endl;
	cout <<"i:...:rUQBBBBBv                                                    igBBBBBBBBBBBBBBZr                                                  iPBBBBQBQBBBQR|" << endl;
	cout <<"           rQBBBX                                               rBBBBBMJ:.   ..iJRBBQBBr                                            2BBBBBBgSJvsjPQBB|" << endl;
	cout <<"              2BBBL                                           uBBQBr                rQBBBY                                       :BBBBMi             |" << endl;
	cout <<"                PBBB                                        :BBBX                      PBBB:                                    BBBBi                |" << endl;
	cout <<"                 :BBB                                      qBBB                          BBQX                                 vBBB:                  |" << endl;
	cout <<"                   BBB                                    gBBY                            JBBg                               PQBb                    |" << endl;
	cout <<"                   :BQI                                  qBBr                              7BBX                             5QBJ                     |" << endl;
	cout <<"                    RBB                                 .BBq                                qBB.                           :BBP                      |" << endl;
	cout <<"                    .BB7                                BBB                                  BBB                           QBB                       |" << endl;
	cout <<"                     BBg                                QB1                                  KBB                          .BBv                       |" << endl;
	cout <<"                     BBQ                               iBB:                                  :BBi                         1BB                        |" << endl;
	cout <<"                     BBE                               rBB.                                  .BBr                         bBB                        |" << endl;
	cout <<"                    .BBr                               :BB:                                  iBQ:                         SBB                        |" << endl;
	cout <<"vLvsLJsjs1jU122IU2siBBB                                 BBq                                  ZQB                          :BB:                       |" << endl;
	cout <<"QRQRQgMDgDDEZddPP27BBB7                                 gBB.i7YLjJ1u11I252S5X5KSKXqKbPdbEbdULBBb                           BBQ        . .............|" << endl;
	cout <<"                   BBR                                   BQB5PZgDgDgDgEDdZPdPPKqXqSX5S2I1j7rBBB                            LBBQBBBBBBBBBBBBBBBQBBBBBB|" << endl;
	cout <<"                 rBBB                                    :BBY                              JBB:                             BBB                      |" << endl;
	cout <<"                MBBq                                      rBBR                            QBBr                               BQB.                    |" << endl;
	cout <<"              dBBB:                                        .BBBi                        rBBB.                                 QBB2                   |" << endl;
	cout <<"           jBBQB7                                            ZBBQr                    rBBBP                                    vBBBv                 |" << endl;
	cout <<"vri:i7uZBBBBBZ:                                                gBBBgi              iQQBBg                                        XBBBd:              |" << endl;
	cout <<"QBQBQBBBBQv.                                                     YBBBBBBZIL7rs2DBBBBBBv                                            YBBBBQPr:     .:JR|" << endl;
	cout <<"  ..                                                                :IBBBBBBBBBBBBI:                                                  7RBQBBBBBQBBBBB|" << endl;
	cout <<"                                                                                                                                           .:77vr:.  |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                          :vUu.                             ..                                                                       |" << endl;
	cout <<"                                         Kq. .Zr :7sj1sLi.             .uS2IYj2q7                                                                    |" << endl;
	cout <<"                                         Q    vB27i.....7qZ:     . rXjSP:       YB:                                                                  |" << endl;
	cout <<"                                         Q. 1Dr           .bZ 7RUM2U              Bi  .iirrrii..                                                     |" << endl;
	cout <<"                                          QBr               rQg.r                  BPri::::::rvuS2s:                                                 |" << endl;
	cout <<"                                         .B        :1        JD                    :B             :v2qJ:                                             |" << endl;
	cout <<"                                         Q.        .B  7P     B.                    QPrvu15jr         .vdL                                           |" << endl;
	cout <<"                                         B       i.    Br     rR                    I:     .rXq7         IB                                          |" << endl;
	cout <<"                                        ig       iU     Xi     B                    Z.         rPPr   Yu7.B7                                         |" << endl;
	cout <<"                                         B        :  X         B                    B7i7ri:.      sD7Br   Q.                                         |" << endl;
	cout <<"                                         SP         .B        :D                   UB ..:irvIXJ.    rPjuuI.                                          |" << endl;
	cout <<"                                          SP         .        XB7JuKqUuIUUj2suYsvvJBb         :2bu                                                   |" << endl;
	cout <<"                                           7Br                B v..          .....  .2Pv         :EK                                                 |" << endl;
	cout <<"                                           Q r51Y2L11I2s.    B:                        rbP:        iQ.                                               |" << endl;
	cout <<"                                           B    .Q     rEX7vQ:                           .qdr       7B.                                              |" << endl;
	cout <<"                                           :gY:id7        ::                                sM7     g.B                                              |" << endl;
	cout <<"                                             .ii                                              2Q   r2 UU                                             |" << endl;
	cout <<"                                                                                               :B: :5 vK                                             |" << endl;
	cout <<"                                                                                                 R1 g Zr                                             |" << endl;
	cout <<"                                                                                                  iIBZE                                              |" << endl;
	cout <<"                                                                                                     .                                               |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"                                                                                                                                                     |" << endl;
	cout <<"-----------------------------------------------------------------------------------------------------------------------------------------------------|" << endl;

	cout << endl;
	cout << endl;
	cout << endl;
	cout <<"변기에 빠진 도리베어는 정신을 차려보니 팔이 사라진 채 하수구에 쓰러져있었어요.                                                    (넘어갈려면 키 입력)";
	cout << endl;
	cout << endl;
	cout << endl;
	_getch();
	system("cls");


	cout <<"                    iBB7                                7BBv                               BBB                               BBB                     |" << endl;
	cout <<"                     BBB                                BBB                                 BBq                             .BBU                     |" << endl;
	cout <<"                     jBB                               vQB.                                 XBB                             BBB                      |" << endl;
	cout <<"                     :QB:                              BBB                                   BBv                            BBL                      |" << endl;
	cout <<"                     .BBi                              BBQ                                   BBE                           7BB                       |" << endl;
	cout <<"                     rBB.                              BBM                                   BBE                           LBB                       |" << endl;
	cout <<"                     QBQ                               BBB                                   BQu                           rBB.                      |" << endl;
	cout <<"QQQBBBBBBBBBBBBBBBBgPBQU                               sBB                                  vBB                             BB1                      |" << endl;
	cout <<"v7v77r7rrrririii::..BBB                                 BBB2gBQBBBBBBBBBBBBBBBBBQBBBBBBBBBBZBBB                             BBB.:rr77vvvvYYsYjsuj112U|" << endl;
	cout <<"                   gBB                                  vBBQ.irr7rrrririiii:i::::::::....  BBQ                               BBBKgQBBQBQBQQMQMMgMZDZZ|" << endl;
	cout <<"                  BBB.                                   EBB.                             uBBi                               LBB:                    |" << endl;
	cout <<"                UBBB                                      EBBU                           BBBr                                 2BB5                   |" << endl;
	cout <<"              SBBQL                                        vQBB:                       LBBB.                                   rBBQ.                 |" << endl;
	cout <<"          .5QBBBs                                            RBBBr                   uBBBU                                       BBBB.               |" << endl;
	cout <<"BBRPEDBBBQBBBE:                                               .gQBBBL.           :IBQBBI                                          .BBBBK.            |" << endl;
	cout <<"BBQBQBBBBSi                                                      rBBBQBBBBBQBBBBBBBBg:                                               5BBBBBRSvrii7JqB|" << endl;
	cout <<"                                                                     rXBBBBBBBBQ1i                                                      rDQBBBBBBBBBB|" << endl;
	cout <<"                                 .iii:.                                                                                                              |" << endl;
	cout <<"                              .ISsiiirLX5.              iYLLr:          ..::::...            .::                                                     |" << endl;
	cout <<"                             rg.        :Qr           1br...:r1LirK5PUUJs77r7r7vJu51Yi     vPsr7Ev                                                   |" << endl;
	cout <<"                             Pr           B          YD       iBv...                .7SP::X:     gL                                                  |" << endl;
	cout <<"                             .B           B          B      .d2                         rBI       B                                                  |" << endl;
	cout <<"                            iE.          Ss          Zs    jg.                        .   .Kq:    B                                                  |" << endl;
	cout <<"                            B            .:r          5Pi PI                       I  sQ :. .dP  :B         .Y2j1                                    |" << endl;
	cout <<"                            Pv           YQB            .Z5                     ..7B   L7i    LB7X         Yd:  :QbJjJ                               |" << endl;
	cout <<"                             Qv    .Ms  .MQ             YP                      Ur.       .    uB         iQ      s  rBr                             |" << endl;
	cout <<"                              7u1Ujv:B SS.             MU                         7YP. vgr7     LZ        :g           PI                            |" << endl;
	cout <<"                                     UQ.             rB.                          . :B 1Y        Rr        Q.           B                            |" << endl;
	cout <<"                                                    qZ                               s            B         g.          Q.                           |" << endl;
	cout <<"                                                   gU                                             5U       I7B         Lg                            |" << endl;
	cout <<"                                                  Ms             .                                 B       MK: :     :PK                             |" << endl;
	cout <<"                                                 PU             .j1u2I:      7sJ2USr               B        iBv5K7LuXu.                              |" << endl;
	cout <<"                                                :B                                                 B             ..                                  |" << endl;
	cout <<"                                                B.                                                rg                                                 |" << endl;
	cout <<"                                                Q                        :::                      B.                                                 |" << endl;
	cout <<"                                                B                      DB...B7                   iQ                                                  |" << endl;
	cout <<"                                                15                      r7 rI.                   B                                                   |" << endl;
	cout <<"                                                 B                      rQB.                    B.                                                   |" << endl;
	cout <<"                                                 :Q                  .jDi  gr                  B:                                                    |" << endl;
	cout <<"                                                  rB.                77     S5               :B:                                                     |" << endl;
	cout <<"                                                   .ZX.                                    :PE                                                       |" << endl;
	cout <<"                                                     .5Ks:                               7ES.                                                        |" << endl;
	cout <<"                                                        :vU5uLi.                      rqq7                                                           |" << endl;
	cout <<"                                                            ..i77BqjuLvrrii::...::rsBLi                                                              |" << endl;
	cout <<"                                                                rI   ..::rr77v7v7r: vI                                                               |" << endl;
	cout <<"                                                               .B                    5U                                                              |" << endl;
	cout <<"                                                              7P                       B                                                             |" << endl;
	cout <<"                                                              Q.                       Ij                                                            |" << endl;
	cout <<"                                                             :g                         Q.                                                           |" << endl;
	cout <<"                                                             :Z                         s5                                                           |" << endl;
	cout <<"                                                             iE                          B                                                           |" << endl;
	cout <<"                                                             :D                          R.                                                          |" << endl;
	cout <<"                                                              B                          Zr                                                          |" << endl;
	cout <<"------------------------------------------------------------------------------------------------------------------------------------------------------" << endl;
	cout <<"" << endl;
	cout <<"" << endl;
	cout <<"" << endl;
	cout <<"과연 도리베어는 팔을 찾고 공주님을 물리칠 수 있을까요?                                                                            (넘어갈려면 키 입력)";
	cout <<"" << endl;
	cout <<"" << endl;
	cout <<"" << endl;
	_getch();
	system("cls");

}
void Scene::show_Sewer() {
	system("cls");
	printf("                        ..,,..                                                                                                                       \n");
	printf("                   :;rr;i::::ii;rr:                                   .:i;;;;;;;;i:.                                   ,;rr;iiiii;;rri.              \n");
	printf("                :77i...,:i;;ii,.  ,rXi                             :77;:..........,;7r:                             :77i...,::i::,.  ,;Xr.           \n");
	printf("              iS;  iXXri:,..,:irXX;  :Xr                         rXi  :r777rrrr777;,  iX;                         iXi  i7X7;i::::irXXr, .7X,         \n");
	printf("             Sr .XSi              :XS, :2:                     ;S, :XX;.          ,rSX, :S;                     ,Si ,SXi             ,72r  XX        \n");
	printf("           i2  2S.                   Xa  X7                   2; iar                 .X2. rS                   rS  2X                   iar ,2.      \n");
	printf("          i2 ,8:                      .Z; rX                .a  aX       i:, ,::        2X .a.                X7 ;Z.                      7Z  a,     \n");
	printf("         ,a :8                          ar 77               Z  8:       r,   . ,;ii      rZ  Z               rX 72                         :8  Z.    \n");
	printf("         Z  B                            8, a,             a. 0.    :ii,          ;r7.    ;Z ,a             .Z iZ                           ,8 .a    \n");
	printf("        a  8                              Z: a            a  8       X@@B;     iZZZi        0  a            a rX                              0 .a   \n");
	printf("        a ;X                              ;X Xi           a 77     i------:    i-----i,     a: a           iX a,                              Z. a   \n");
	printf("        a 77                              i2 7;          :S 2:     |      Xi iX:     |      Xr S,          ;r Z                               2i a   \n");
	printf("        a ;X                              rX Xi          ,S 2i    ,|      X  ;r      |      Xr 2.          i7 Z.                              a, Z   \n");
	printf("        a  8                              a, a            a rX     r------r,   r------r     Z. Z            a 77                              8  a   \n");
	printf("        ;X a; ..........,,,...,:,,,,,,,,.i8 .2            a  0            r,,,,i.           8 .2            a  0                             7X 7;   \n");
	printf("         Z  Wi:ir;i;;r7;iiirrrii;rri;rr,,W. Z.            :2 XX      ＼     .      /       Zi 2,            ,2 r0i;;r777rrr7Xr;77Xr;XXrrXXr;7W  Z    \n");
	printf("         .Z .0  7;   ;;;   ;:;   ;; .:: 2i Xr              Si Zi       -----------        XS ;X              X; 2X .;7;   rX:  r7. :7i ,:;  8  a,    \n");
	printf("          :2  a:,:   ,,;   ;,;   ii  .;8: 7X                a, ar           .;           SS :a                S; 7ai,   .;r   ;r  ,i;  i. ,Z  2;     \n");
	printf("           :2  XZX   ,:i   ;.;   i:  8S  S7                  2i X2.                    :Z; ;2                  X7 :8;  ,;;   rr  ,i;  : 7XS  2i      \n");
	printf("             X7  SXi  ,:   i i   rX2X. iS:                    7X  SX:                iSX  X7                    iS. iXS7:   ;;  .:.  ,SX2  ;S.       \n");
	printf("              :Xr  i7XSS;,.XiSirXXi  iX;                       ,X;  rX7i.        ,;XX;  rX,                       7X, .77rrSX, ,X:Si7Xi  ;Xi         \n");
	printf("                ,r7i.  ,,:ii::,.  :7Xi                           :X7, .:;r777777r;:  ,7X,                           ;X;. .,:ii;rii,.  ,77:           \n");
	printf("                   ,;rr;ii:::i;rr;,                                 irri:,.......:;77i                                .irr;i:,:,::i;r;:              \n");
	printf("                         ....                                          .,:ii;;ii:,                                          .,,,..                   \n");
	printf("                                                                                   :::,                                                              \n");
	printf("                                                                  ii::ii :iiiiii,,r   :;                                                             \n");
	printf("                                                                 ;,   ;i        .ir:   .r                                                            \n");
	printf("                                                                .r   r.            ,r.  ;,                                                           \n");
	printf("                                                                .r  ;,               ;i,;                                                            \n");
	printf("                                                                 ,iir                 ;;                                                             \n");
	printf("                                                                   7                   ii                                                            \n");
	printf("                                                                  ;,                    r.                                                           \n");
	printf("                                                                 .r                     i:                                                           \n");
	printf("                                                                 ::                     i,                                                           \n");
	printf("                                                                 i,                     7                                                            \n");
	printf("                                                                 ,r                   :;.                                                            \n");
	printf("                                                                  i;,              .,i:                                                              \n");
	printf("                                                                    ,:;Xi::iiiiiii:;S:                                                               \n");
	printf("                                                                      ;;i           X                                                                \n");
	printf("                                                                       r:           ri                                                               \n");
	printf("                                                                       i,            ;,                                                              \n");
	printf("                                                                       i:            ;.                                                              \n");
	printf("                                                                       r             ;,                                                              \n");
	printf(":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::\n");
	control.gotoxy(0, 50);
	printf("▶ 왼쪽 하수구");
	control.gotoxy(0, 51);
	printf("   가운데 하수구");
	control.gotoxy(0, 52);
	printf("   오른쪽 하수구");
}

void Scene::show_crossroads() {
	system("cls");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                       :77vvvvL77i.                                                                 |\n");
	printf("                                                                    iUYi.       .:7us:                                                              |\n");
	printf("                                                                  rXr                rSv                                                            |\n");
	printf("                                                                 q7                    iK7                                                          |\n");
	printf("                                                               .d.                       LP                                                         |\n");
	printf("                                                              :d                          .g.                                                       |\n");
	printf("                                                             .Z                             R.                                                      |\n");
	printf("                                                             M                        .      Q                                                      |\n");
	printf("                                                            D.       .                .Ir    .D                                                     |\n");
	printf("                                                           vv       r:                  uM    sv                                  :vsv7vsJ.         |\n");
	printf("                                                           g      .2.                    :Br   g                                r2v.     .uS        |\n");
	printf("                                                          sr     LS                        BM  .P                             iqr          :D       |\n");
	printf("                                                          g     E1                          UB. X.                           Ss             iS      |\n");
	printf("               ..:..                                     :J    B7                            .B7 E                         ib.               D.     |\n");
	printf("            :YJri::i7sJi                                 U:  iB.                               1Yu:                       s5                 i2     |\n");
	printf("           X7.         ijU.                              P  UB                                  .PQ                      Sv                   E     |\n");
	printf("          g.             .jI.                            7 KK                                     P5                    Pr                    g     |\n");
	printf("         X:                .12                           LJr                                       iK7                 di                     D     |\n");
	printf("         d                   :Pi                       .YQ.                                          rP7              Pr                      g     |\n");
	printf("        iJ                     uI                    i2U.                                              7Pr           JL                      .q     |\n");
	printf("        77                      :d.                7Kv                                                   7Pi        :P                       rs     |\n");
	printf("        iY                        Pi            .UIi                                                       vqi      D        .:.             P.     |\n");
	printf("        .5                .ir:.    2v         rIj.                                                           Lq:   J:   .rUIUr:              g      |\n");
	printf("         D                   :rY7i  7s     .vXr                                                                JS. U rSgPv.                 :S      |\n");
	printf("         K.                      :7r.X1  :IU:                                              BBBB                  7BR7i.                     b.      |\n");
	printf("         rY                           EKjY                           .:          BLBi     BB  BB                   r                        g       |\n");
	printf("          g                            i                            PDvMEQusqX5UPB: B        BB                                            vv       |\n");
	printf("          ji                                                        B  5B         IBE       BB                                             Q        |\n");
	printf("           g                                                        1U7B           .B                                                     :X        |\n");
	printf("           7s                                                        uB             :B      BB                                            P.        |\n");
	printf("            E.                                                      Bg  uX:  .PR2    B                                                    M         |\n");
	printf("             g                                                     BP                B                                                   Y7         |\n");
	printf("             .D                                                    B.     rQRr      2B                                                   M          |\n");
	printf("              .P                                                   XB      r5.     7B                                              :Y   :K          |\n");
	printf("                v:                                                  MBr          :BB                                                rK7 X           |\n");
	printf("               :Kv                                                   .KME57LrJ5dBB                                                    iZd           |\n");
	printf("             vXr                                                          BIii.  B                                                      iSr         |\n");
	printf("          .U2i                                                           7Q      rB                                                       7Pi       |\n");
	printf("        rSJ.                                                             Q        BP                                                        vqi     |\n");
	printf("     .YXi                                                               iB         B.                                                         LP:   |\n");
	printf("   :2u:                                                                 M2         rB                                                           sS: |\n");
	printf(" :U7                                                                    Bi          B                                                             YL|\n");
	printf("----------------------------------------------------------------------------------------------------------------------------------------------------|\n");
	control.gotoxy(0, 50);
	printf("▶ 왼쪽 길");
	control.gotoxy(0, 51);
	printf("   가운데 길");
	control.gotoxy(0, 52);
	printf("   오른쪽 길");
}
void Scene::show_room() {
	system("cls");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("              .:iiriiir:.                                                                                                                           |\n");
	printf("         .:7ri:..      :i77r.                                                                                                                       |\n");
	printf("       i7i.                .i77r.                                                                                     .rir7r7r777777:               |\n");
	printf("     .:                        .r77:                                                                                  :BSirrrrrrrrrBS               |\n");
	printf("     M.                            :77:                                                                                 7.        :r                |\n");
	printf("     Xrir7i.                         .i7i                                                                               0:        .2                |\n");
	printf("     7    .:r77i:.        .:irrrrii:i:::287                                                                          :77.           77:             |\n");
	printf("     7.        .:rr7r:. .i:.           . :2X                                                                      .77r                :77.          |\n");
	printf("     7:             ..ii07::iiriiii::::..  2i                                                                   .27.                    .72.  ......|\n");
	printf("rrii:X:                 7:                 77irrirrririrrririrrrrrrririririririririiiiiririririrrrrrirrrrririi:BS.                         2Bi.::i::|\n");
	printf("     :r                 7.                 2                                                                  2r                            .X      |\n");
	printf("     ir                 2.                 S                        ......................                   72                              .8     |\n");
	printf("     :2                 2                  S                 ...::i70....8  .i0  :S   S   r.  2.i7Xr.        B                                0:    |\n");
	printf("      77ri:.            2                  X              .77i.22   Z    0   .r   7   2   77i0BBBBBBBB:      B                                27    |\n");
	printf("         .:irrri:.      2                  2             .Z    :0   B    0   .2 .iB70MBBBBBBBBBBB82i.        S7                               M.    |\n");
	printf("               .:ir7r:. X        ....:::::rX            .XBiiiir2iii2riiiBBBBBBBBBBBBBBBBBBBBBr               02                             r2     |\n");
	printf("                     .::2iririiii::::.:....                               iX008MBBM0X2227i:.:                  70r                          iX      |\n");
	printf("                                                                                                                 7X2.                     .27       |\n");
	printf("                                                                                                                   :2S7.               .r7r         |\n");
	printf("                                                                                                                      :27ii:::.:::::i77r.           |\n");
	printf("                                                 ...            777727:                                                   ..::iii::..               |\n");
	printf("                                              .S7i::XS:rr777ri.B     .70                                                                            |\n");
	printf("                                              B    7:.      ..iS2r.    :B                                                                           |\n");
	printf("                                              27. 7i             :2X: .0r                                                                           |\n");
	printf("                                               .riB                 7B7                                                                             |\n");
	printf("                                                  X                   M.                                                                            |\n");
	printf("                                                 M                     B                                                                            |\n");
	printf("                                                M.                     S7                                                                           |\n");
	printf("                                               8.                      87                                                                           |\n");
	printf("                                              .B                     .02                                                                            |\n");
	printf("                                               :227:.              :XX.                                                                             |\n");
	printf("                                                  .i77227r277777r2BS                                                                                |\n");
	printf("                                                         .B. .... .77                                                                               |\n");
	printf("                                                         B          :M:                                                                             |\n");
	printf("                                                        iM            Bi                                                                            |\n");
	printf("                                                        0r             B.                                                                           |\n");
	printf("                                                        B.             :B                                                                           |\n");
	printf("-----------------------------------------------------------------------------------------------------------------------------------------------------\n");
}
void Scene::show_BossIntro() {
	system("cls");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                    iijVi s           iiiiiirrriiii         iv  Xriri                                               |\n");
	printf("                                                 rvi   L  iJiubBBBBBQBBBBBBBQBBBBBBBBBBBBBRqd   s   ivri                                            |\n");
	printf("                                              ivv     iv   BBBBBBBBBBBBBBBBBBQBBBQBBBBBBBQBBB   u      iLi                                          |\n");
	printf("                                            iJi        s   BBBQBBBQBBBBBBBBBBBBBQBBBQBQBQBBBB   u        isi                                        |\n");
	printf("                                           sr         iY   BBBBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBB   U          iui                                      |\n");
	printf("                                         vJ            J   BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBB   u            Yv                                     |\n");
	printf("                                        Ui            iY   BBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBB   k             iI                                    |\n");
	printf("                                       K               j   BBBBBQBBBQBBBBBBBBBBBBBBBBBQBBBBBB   u               Vi                                  |\n");
	printf("                                      K                s   BBQBBBBBQBBBQBQBBBBBBBBBBBBBBBBBBB   k                Si                                 |\n");
	printf("                                     P                 u   BBBBBBBBBBBBBBBBBQBBBQBBBBBQBBBBBB   U                 Ki                                |\n");
	printf("                                    d                  s   BBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBB   I                  P                                |\n");
	printf("                                   b                   u   BBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBB   U                   P                               |\n");
	printf("                                  qi                   J   QBBBBBBBBBBBQBBBQBBBQBBBBBBBBBBBBB   I                   iK                              |\n");
	printf("                                 Jr                    u   BBBBBQBBBBBBBBBBBBBBBBBBBBBBBQBBBB   k                    iu                             |\n");
	printf("                                rJ                     j   BBBBBBBBBBBBBBQBBBQBBBBBBBBBBBBBBB   k                     sr                            |\n");
	printf("                               iK                      u   BQBQBBBBBBBBBBBQBBBBBBBQBBBBBBBBBQ   U                      Ki                           |\n");
	printf("                               d                       J   BBQBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBB   V                       Z                           |\n");
	printf("                              Ui                       u   BQBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBB   k                       iV                          |\n");
	printf("                              q                        J   QBBBBBBBBBBBBBBBQBQBBBBBBBBBBBBBBB   V                        S                          |\n");
	printf("                             S                         u   BQBBBBBBBBBBBQBBBBBQBBBBBBBBBBBBBB   k                         U                         |\n");
	printf("                             X                         u   BBBBBBBBBBBBBBQBBBBBBBBBQBBBBBQBBB   V                         q                         |\n");
	printf("                            rr                         u   BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB   I                         rr                        |\n");
	printf("                            K                          u   BBBBBBBBBBQBBBBBBBBBBBBBQBBBBBBBBB   V                          S                        |\n");
	printf("                            S                          U   BBBBBBBBBBBBBBBBBQBBBBBQBBBBBBBBBB   I                          K                        |\n");
	printf("                           iv                          u   BBBBBBBBQBBBBBBBBBQBBBBBBBQBQBBBBB   I                          vi                       |\n");
	printf("                           u                           I   BBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBB   S                          iY                       |\n");
	printf("                           I                           k   BBBBBBQBBBBBBBQBBBBBBBBBBBBBQBBBBB   X                           S                       |\n");
	printf("                           I                           u   BBBBBBBBBBBQBBBBBBBBBBBBBBBQBBBBBB   I                           k                       |\n");
	printf("                          iv                    qirY   u   BBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBQ   S   Viid                    vi                      |\n");
	printf("                          vi                    Z  Pi  k   BBBBBQBBBBBQBBBQBBBBBBBQBBBBBBBQBg   I  vu  g                    iv                      |\n");
	printf("                          u                     Z  Zi  U   BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQ   V  iE iX                     s                      |\n");
	printf("                          k                      vri   I   BBBBBBBBBBBBBQKZRMBBBBBQi   IBBBBQ   V    ii                      U                      |\n");
	printf("                          V                            U   BBBBBBg    Di         ii     BBBBB   S                            k                      |\n");
	printf("                          U                            k   BBBBBQK   vi             vv  BBBBB   I                            V                      |\n");
	printf("                          U                            k   BBBBBBBBqur                XBBBBBB   X                            u                      |\n");
	printf("                          s                            V   BBBBBBBBR                   BQBBBB   V                            u                      |\n");
	printf("                         iv                            U   QBBBBBL                     BBBBQB   X                            L                      |\n");
	printf("                         ir                            V   BBBBBB                    iBBBBBBR   V                            vi                     |\n");
	printf("                         ri                            k   BBBBBBBX              iiiBBBBBQBBQ   S                            ii                     |\n");
	printf("                         vi                            V   BBBQBBBBBBbviii iirrrii   BBBQBBBM   I                            ii                     |\n");
	printf("                         v                             k   BBBBBBQBBBBBBBB            BBBBBBM   X                            iv                     |\n");
	printf("                         L                             V   BQBBBBBQBBBQBQB            RBBBBBM   V                             v                     |\n");
	printf("                         v                             I   BBBBBBBBQBBBBBQ            rBBBBBB   K                             v                     |\n");
	printf("                         Vi                            P   BQBQBBBBBBBQBBQ            iBBBBBQ   V                            ru                     |\n");
	printf("-----------------------------------------------------------------------------------------------------------------------------------------------------\n");
	printf("                                                                 보스전으로 출발합니다");
	Sleep(3000);
}
void Scene::show_Boss() {
	system("cls");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                                                                    |\n");
	printf("                                                                                                     .27    :    :                                  |\n");
	printf("                                                                                              .:ri. iK vX  7QU .bP7                                 |\n");
	printf("                                                                                             2u: .sb7   iXu1 jSb  Pr  :uv77jY                       |\n");
	printf("                                                                                           rP.    2D     .7   b    q.i7     :g                      |\n");
	printf("                                                                                          rX    iJ75:               BB       i5                     |\n");
	printf("                                                                                          R    S7   rssri..     ..7U. YU.     g                     |\n");
	printf("                                                                                          7U  D.       ..:irr777ii.    .d:   2L                     |\n");
	printf("                                                                                           77d:                s         g :Iv                      |\n");
	printf("                                                                                            .R          :D     Mj        .b                         |\n");
	printf("                                                                                            si      .Y.YjM   M2: UIj      d                         |\n");
	printf("                                                                                            K.     .Sj  .2 :iP    LR.     v7                        |\n");
	printf("                                                                                            J: j7:.i    .:.         17  i J:                        |\n");
	printf("                                                                                             qiKv iBQBBBBBBBBBQBBBBB i75QiB                         |\n");
	printf("                                                                                             D ui gBBBBBBBBBBQBBBBBR   i1 g                         |\n");
	printf("                                                                                             v:P  BBQBBBQBBBBBBBBBBB   iDrL                         |\n");
	printf("                                                                                              rS  gBBBBBBQBBBBBBBQBZ   2s                           |\n");
	printf("                                                                                              D    UEQBBBBQBBBBBQBM    R                            |\n");
	printf("                                                                                             i2                      .R.                            |\n");
	printf("                                                                                             LY                    .Yq                              |\n");
	printf("                                                                                              b7                 i1u:                               |\n");
	printf("                                                                                               isj7r::.. ....ri7r.                                  |\n");
	printf("                                                                                                    .:rrPQMvQjbi:.                                  |\n");
	printf("                                                                                                   .ir.g.  .  :J :Uv                                |\n");
	printf("                                                                                                 :27. :i       D   :1Y:                             |\n");
	printf("                                                                                               .2L    uI.    :DSri    rUi                           |\n");
	printf("                                                                                             .s7   .7riIjr777: :sLL:    rK                          |\n");
	printf("                                                                                             uK  iJr iY          Yv:7vrrib                          |\n");
	printf("                                                                                              .ir:  jv            vL                                |\n");
	printf("                                                                                                   d:              u7                               |\n");
	printf("                                                                                                  g.                Q                               |\n");
	printf("                                                                                                 5:                 D                               |\n");
	printf("                                                                                                 D.               .X.                               |\n");
	printf("                       .v7ir  :irri:.  .v77Jr                                                     r5vi.... . ..iiYB.                                |\n");
	printf("                      rS  rgZri:..::rvjQi   :b.                                                    P. .Q2irrriigv  1L                               |\n");
	printf("                     .D  Pi             rX:   Q                                                  .Z   :u        JJ  :qr                             |\n");
	printf("                     ur :I                2j iI                                                 .g   .D          rq   rs7rrP                        |\n");
	printf("                     .P.Lr                 iBi                                                 :Z    R            .d.     .E                        |\n");
	printf("                        D.                  .q                                               Yvi   .M               IJ.  iE                         |\n");
	printf("                       .b                    iq                                             .B    rE                 .vvvr                          |\n");
	printf("                      7b                      Z.                                              77vYr                                                 |\n");
	printf("                    .d7                       vL                                                                                                    |\n");
	printf("                    Q                         E.                                                                                                    |\n");
	printf("                   u7                        iq                                                                                                     |\n");
	printf("                   I:                       rd                                                                                                      |\n");
	printf("                   .M                      Xj                                                                                                       |\n");
	printf("                    ib.                 .Jj.                   ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ-|\n");
	printf("                     .uUr.           .i1vIv                    l                                            l                                       |\n");
	printf("                        :rsLviviri7vJLr   rP                   l                                            l                                       |\n");
	printf("                             :M....        rE                  l                                            l                                       |\n");
	printf("                             q.             7X                 l                                            l                                       |\n");
	printf("                            .d               Kr                l                                            l                                       |\n");
	printf("                            Z.                Q                l                                            l                                       |\n");
	printf("                           .D                 ur               l                                            l                                       |\n");
	printf("                           Kr                 rX               l                                            l                                       |\n");
	printf("-----------------------------------------------------------------------------------------------------------------------------------------------------\n");
}